# This file allows testing your addon using travis CI servers to use it you'll need to
# create an account in travis.org and enable your addon there. 
#
# By default it will test linux 64bit and osx against the master and stable OF branches. 
# Other platforms can be enabled by uncommenting the corresponding sections.
#
# If any extra install is needed to use the addon it can be included in the corresponding
# install script in:
#
# scripts/ci/$TARGET/install.sh
#

env:
  global:
    - APPNAME="colorExample"
    - secure: "pYFIATdNXF/xXJLhn8cMSKyodnNAU4eM8QxdChvkv7rVSjTAJnt7Bar0EpP2joryzcgszCxHKzlOQVm3dCyUJc2KR8Ic6A9EtD+T8FLsFnBFMboyBqIhQtxXk3IhoUn2jqONfnZzjkjldfl7gidR18PvuKxK2TzJH5KgTPX2NPgzkIiX/ETzrym2g9LaXcUB2dPPU9G6k4mRx9h15TwoCd2HQo9+Qi4jCX8nr81yihPen6b/mwim1lu2BRVJCav23qipAI0qbqoun5OL/0f/dNQs5ncIsR7ZnHjVihwqcw7mwsUcTgfI/ySAzsUuAPKK3JeDfeFRd70Lwyy20eQd+QpoJXTZzaloiTy9mNmpmudFZRLW8GlAChj6o7JfWUUaT9ZoZ2jpkeyaJpgcdB2jAxnxbiEKMuPp+AkRgVSwDhYvV8gEVxvo6BADfJI7xikFCvmRF6/3dNE5ZymX9j4jFsRFvTXxbg0FcO7sg5uqHh3lMPUJmSVnjwr7DyyDVEeN7sdMlwKZhf7aZvsmCcrXgVcB3Qk+9+clcNr5JbsULze04wgQhIAVLeZJTNpPSOOP/frP6brNP+WURE1wG5lphLrq3z06WcOx0H6j7ecwFmQfVoXFSb8evKS0pFZGP16sgM5ezkyy74vWpbQkWIhuFDEcxBpy/VDBJL4D0zaPHro="
language: c++
compiler: gcc
sudo: true
matrix:
  include:
  # fully specify builds, include can't dynamically expand matrix entries
  # relative order of sudo and env is important so that addons: is recognized

# Linux 64bit, OF master
  - os: linux
    dist: xenial
    sudo: required
    env: TARGET="linux64" OF_BRANCH="master"
    addons:
      ssh_known_hosts: pong.hku.nl
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - sshpass
          - libssl-dev
          - openssl
#          - gdb

# Linux 64bit, OF stable
  - os: linux
    dist: xenial
    sudo: required
    env: TARGET="linux64" OF_BRANCH="stable"
    addons:
      ssh_known_hosts: pong.hku.nl
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
          - g++-4.9
          - sshpass
          - libssl-dev
          - openssl

# OSX, OF master
  - os: osx
    osx_image: xcode9.2
    compiler: clang
    env: TARGET="osx" OF_BRANCH="stable" MACOSX_DEPLOYMENT_TARGET=10.9
    addons:
      ssh_known_hosts: pong.hku.nl

# OSX, OF stable:  Not supported yet
#  - os: osx
#    osx_image: xcode8
#    compiler: clang
#    env: TARGET="osx" OF_BRANCH="stable"

# Linux ARM6, OF master: Uncomment following lines to enable 
#  - os: linux
#    sudo: required
#    dist: trusty
#    env: TARGET="linuxarmv6l" OF_BRANCH="master"


# Linux ARM6, OF stable:  Not supported yet
#  - os: linux
#    sudo: required
#    dist: trusty
#    env: TARGET="linuxarmv6l" OF_BRANCH="stable"

# Linux ARM7, OF master: Uncomment following lines to enable 
#  - os: linux
#    sudo: false
#    env: TARGET="linuxarmv7l" OF_BRANCH="master"
#    cache:
#      directories:
#        - ~/rpi2_toolchain
#        - ~/firmware-master
#        - ~/archlinux

# Linux ARM7, OF stable:  Not supported yet
#  - os: linux
#    sudo: false
#    env: TARGET="linuxarmv7l" OF_BRANCH="stable"
#    cache:
#      directories:
#        - ~/rpi2_toolchain
#        - ~/firmware-master
#        - ~/archlinux


# Emscripten, OF master: Uncomment following lines to enable 
#  - os: linux
#    sudo: false
#    env: TARGET="emscripten" OF_BRANCH="master"
#    addons:
#      apt:
#        sources:
#          - ubuntu-toolchain-r-test
#        packages:
#          - libstdc++6


# Emscripten, OF stable: Not supported yet
#  - os: linux
#    sudo: false
#    env: TARGET="emscripten" OF_BRANCH="stable"
#    addons:
#      apt:
#        sources:
#          - ubuntu-toolchain-r-test
#        packages:
#          - libstdc++6


# iOS, OF master: Not supported yet
#  - os: osx
#    osx_image: xcode8
#    compiler: clang
#    env: TARGET="ios" OF_BRANCH="master"


# iOS, OF stable: Not supported yet
#  - os: osx
#    osx_image: xcode8
#    compiler: clang
#    env: TARGET="ios" OF_BRANCH="stable"


# tvOS, OF master: Not supported yet
#  - os: osx
#    osx_image: xcode8
#    compiler: clang
#    env: TARGET="tvos" OF_BRANCH="master"


# tvOS, OF stable: Not supported yet
#  - os: osx
#    osx_image: xcode8
#    compiler: clang
#    env: TARGET="tvos" OF_BRANCH="stable"


# Android armv7, OF master: Uncomment following lines to enable 
#  - os: linux
#    sudo: false
#    env: TARGET="android" OPT="armv7" OF_BRANCH="master"
#    cache:
#      directories:
#        - ~/android-ndk-r12b


# Android armv7, OF stable: Not supported yet
#  - os: linux
#    sudo: false
#    env: TARGET="android" OPT="armv7" OF_BRANCH="stable"
#    cache:
#      directories:
#        - ~/android-ndk-r12b


# Android x86, OF master: Uncomment following lines to enable 
#  - os: linux
#    sudo: false
#    env: TARGET="android" OPT="x86" OF_BRANCH="master"
#    cache:
#      directories:
#        - ~/android-ndk-r12b


# Android x86, OF stable: Not supported yet
#  - os: linux
#    sudo: false
#    env: TARGET="android" OPT="x86" OF_BRANCH="stable"
#    cache:
#      directories:
#        - ~/android-ndk-r12b


  # Exclude the default build that would otherwise be generated
  # see https://github.com/travis-ci/travis-ci/issues/1228
  exclude:
    - compiler: gcc

install:
  - git submodule update --init --recursive
  - cd ~
  - git clone --depth=1 --branch=$OF_BRANCH https://github.com/openframeworks/openFrameworks
  - cd openFrameworks
# fails so we do it ourselves - scripts/ci/$TRAVIS_OS_NAME/install.sh
  - if [ "$TARGET" == "linux64" ]; then 
      sudo scripts/linux/ubuntu/install_dependencies.sh -y;
      if [ -f scripts/linux/download_libs.sh ]; then 
        scripts/linux/download_libs.sh;
      fi;
    elif [ "$TARGET" == "osx" ]; then
      brew update;
      brew upgrade coreutils;
      brew install https://raw.githubusercontent.com/kadwanev/bigboybrew/master/Library/Formula/sshpass.rb;
      if [ -f scripts/$TARGET/download_libs.sh ]; then 
        scripts/$TARGET/download_libs.sh;
      fi
    fi
#  - scripts/linux/compileOF.sh
  - if [ "$TARGET" == "linux64" ]; then
      cd libs/openFrameworksCompiled/project;
      make Debug;
    fi

script:
#  - scripts/ci/addons/build.sh
  - cd $TRAVIS_BUILD_DIR/..
  - mv $APPNAME ~/openFrameworks/apps/devApps/
  - cd ~/openFrameworks/apps/devApps/$APPNAME
  - make Debug
  - cd ..
  - mv $APPNAME $TRAVIS_BUILD_DIR 
  - cd $TRAVIS_BUILD_DIR;

git:
  depth: 256

